# Generated by Django 3.0 on 2020-07-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20200716_2117'),
        ('accounts', '0004_auto_20200716_2039'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
