# Generated by Django 3.0.8 on 2020-07-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistrycategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
