# Generated by Django 3.0.8 on 2020-07-31 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0002_artistrycategory_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolio',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='artistportfolio',
            unique_together={('business_owner', 'business_name')},
        ),
    ]
