# Generated by Django 3.0.8 on 2020-07-31 13:22

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20200731_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolio',
            name='phone_number',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
