# Generated by Django 3.0.8 on 2020-08-02 21:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20200731_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistrycategory',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
