# Generated by Django 3.0.8 on 2020-08-02 21:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0006_auto_20200803_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolio',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1000),
        ),
    ]
