# Generated by Django 3.0.8 on 2020-08-02 22:40

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_auto_20200803_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='artistrycategory',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=1000, null=True),
        ),
    ]
