# Generated by Django 3.0.8 on 2020-08-04 12:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_auto_20200804_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistportfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=10000),
        ),
    ]
