# Generated by Django 3.0.8 on 2020-08-05 11:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0012_auto_20200804_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistportfolio',
            name='portfolio_image',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='artistportfolio',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=10000, null=True),
        ),
    ]
