# Generated by Django 3.0.8 on 2020-08-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0013_auto_20200805_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistportfolio',
            old_name='portfolio_image',
            new_name='portfolio_images',
        ),
    ]
