# Generated by Django 3.0.8 on 2020-07-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
