# Generated by Django 3.0.8 on 2020-08-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='is_rejected',
        ),
    ]
