# Generated by Django 3.0.8 on 2020-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_is_rejected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
