# Generated by Django 3.0.8 on 2020-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20200818_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
